package com.neu.mapper;

import com.neu.entity.Comreview;
import com.neu.entity.ComreviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComreviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    long countByExample(ComreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    int deleteByExample(ComreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    int insert(Comreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    int insertSelective(Comreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    List<Comreview> selectByExample(ComreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    //修改方法
   List<Comreview> selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Comreview record, @Param("example") ComreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Comreview record, @Param("example") ComreviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Comreview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Comreview record);
}