package com.neu.mapper;

import com.neu.entity.InformationManagement;
import com.neu.entity.InformationManagementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InformationManagementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_management
     *
     * @mbg.generated
     */
    long countByExample(InformationManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_management
     *
     * @mbg.generated
     */
    int deleteByExample(InformationManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_management
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_management
     *
     * @mbg.generated
     */
    int insert(InformationManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_management
     *
     * @mbg.generated
     */
    int insertSelective(InformationManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_management
     *
     * @mbg.generated
     */
    List<InformationManagement> selectByExample(InformationManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_management
     *
     * @mbg.generated
     */
    InformationManagement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_management
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InformationManagement record, @Param("example") InformationManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_management
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InformationManagement record, @Param("example") InformationManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_management
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InformationManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_management
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InformationManagement record);
   /* List<InformationManagement> getAll();
*/    
}