package com.neu.mapper;

import com.neu.entity.LargerCategory;
import com.neu.entity.LargerCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LargerCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table largercategory
     *
     * @mbg.generated
     */
    long countByExample(LargerCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table largercategory
     *
     * @mbg.generated
     */
    int deleteByExample(LargerCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table largercategory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table largercategory
     *
     * @mbg.generated
     */
    int insert(LargerCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table largercategory
     *
     * @mbg.generated
     */
    int insertSelective(LargerCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table largercategory
     *
     * @mbg.generated
     */
    List<LargerCategory> selectByExample(LargerCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table largercategory
     *
     * @mbg.generated
     */
    LargerCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table largercategory
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LargerCategory record, @Param("example") LargerCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table largercategory
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LargerCategory record, @Param("example") LargerCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table largercategory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LargerCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table largercategory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LargerCategory record);
}