package com.neu.mapper;

import com.neu.entity.PublicManagement;
import com.neu.entity.PublicManagementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublicManagementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_management
     *
     * @mbg.generated
     */
    long countByExample(PublicManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_management
     *
     * @mbg.generated
     */
    int deleteByExample(PublicManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_management
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_management
     *
     * @mbg.generated
     */
    int insert(PublicManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_management
     *
     * @mbg.generated
     */
    int insertSelective(PublicManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_management
     *
     * @mbg.generated
     */
    List<PublicManagement> selectByExample(PublicManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_management
     *
     * @mbg.generated
     */
    PublicManagement selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_management
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PublicManagement record, @Param("example") PublicManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_management
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PublicManagement record, @Param("example") PublicManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_management
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PublicManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public_management
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PublicManagement record);
}