package com.neu.mapper;

import com.neu.entity.Securityquestion;
import com.neu.entity.SecurityquestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SecurityquestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityquestion
     *
     * @mbg.generated
     */
    long countByExample(SecurityquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityquestion
     *
     * @mbg.generated
     */
    int deleteByExample(SecurityquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityquestion
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityquestion
     *
     * @mbg.generated
     */
    int insert(Securityquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityquestion
     *
     * @mbg.generated
     */
    int insertSelective(Securityquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityquestion
     *
     * @mbg.generated
     */
    List<Securityquestion> selectByExample(SecurityquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityquestion
     *
     * @mbg.generated
     */
    Securityquestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityquestion
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Securityquestion record, @Param("example") SecurityquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityquestion
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Securityquestion record, @Param("example") SecurityquestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityquestion
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Securityquestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table securityquestion
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Securityquestion record);
}