package com.neu.mapper;

import com.neu.entity.SmallCategory;
import com.neu.entity.SmallCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmallCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallcategory
     *
     * @mbg.generated
     */
    long countByExample(SmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallcategory
     *
     * @mbg.generated
     */
    int deleteByExample(SmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallcategory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallcategory
     *
     * @mbg.generated
     */
    int insert(SmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallcategory
     *
     * @mbg.generated
     */
    int insertSelective(SmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallcategory
     *
     * @mbg.generated
     */
    List<SmallCategory> selectByExample(SmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallcategory
     *
     * @mbg.generated
     */
    SmallCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallcategory
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SmallCategory record, @Param("example") SmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallcategory
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SmallCategory record, @Param("example") SmallCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallcategory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmallCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smallcategory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmallCategory record);
}