package com.neu.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ComreviewExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comreview
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comreview
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comreview
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    public ComreviewExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comreview
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comreview
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserEqualTo(User value) {
            addCriterion("user_id =", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotEqualTo(User value) {
            addCriterion("user_id <>", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThan(User value) {
            addCriterion("user_id >", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserGreaterThanOrEqualTo(User value) {
            addCriterion("user_id >=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThan(User value) {
            addCriterion("user_id <", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserLessThanOrEqualTo(User value) {
            addCriterion("user_id <=", value, "user");
            return (Criteria) this;
        }

        public Criteria andUserIn(List<User> values) {
            addCriterion("user_id in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotIn(List<User> values) {
            addCriterion("user_id not in", values, "user");
            return (Criteria) this;
        }

        public Criteria andUserBetween(User value1, User value2) {
            addCriterion("user_id between", value1, value2, "user");
            return (Criteria) this;
        }

        public Criteria andUserNotBetween(User value1, User value2) {
            addCriterion("user_id not between", value1, value2, "user");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andCommodityIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andCommodityIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityEqualTo(Commodity value) {
            addCriterion("goods_id =", value.getId(), "commodity");
            return (Criteria) this;
        }

        public Criteria andCommodityNotEqualTo(Commodity value) {
            addCriterion("goods_id <>", value, "commodity");
            return (Criteria) this;
        }

        public Criteria andCommodityGreaterThan(Commodity value) {
            addCriterion("goods_id >", value, "commodity");
            return (Criteria) this;
        }

        public Criteria andCommodityGreaterThanOrEqualTo(Commodity value) {
            addCriterion("goods_id >=", value, "commodity");
            return (Criteria) this;
        }

        public Criteria andCommodityLessThan(Commodity value) {
            addCriterion("goods_id <", value, "commodity");
            return (Criteria) this;
        }

        public Criteria andCommodityLessThanOrEqualTo(Commodity value) {
            addCriterion("goods_id <=", value, "commodity");
            return (Criteria) this;
        }

        public Criteria andCommodityIn(List<Commodity> values) {
            addCriterion("goods_id in", values, "commodity");
            return (Criteria) this;
        }

        public Criteria andCommodityNotIn(List<Commodity> values) {
            addCriterion("goods_id not in", values, "commodity");
            return (Criteria) this;
        }

        public Criteria andCommodityBetween(Commodity value1, Commodity value2) {
            addCriterion("goods_id between", value1, value2, "commodity");
            return (Criteria) this;
        }

        public Criteria andCommodityNotBetween(Commodity value1, Commodity value2) {
            addCriterion("goods_id not between", value1, value2, "commodity");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeIsNull() {
            addCriterion("comreview_time is null");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeIsNotNull() {
            addCriterion("comreview_time is not null");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeEqualTo(Date value) {
            addCriterion("comreview_time =", value, "comreviewTime");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeNotEqualTo(Date value) {
            addCriterion("comreview_time <>", value, "comreviewTime");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeGreaterThan(Date value) {
            addCriterion("comreview_time >", value, "comreviewTime");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("comreview_time >=", value, "comreviewTime");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeLessThan(Date value) {
            addCriterion("comreview_time <", value, "comreviewTime");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeLessThanOrEqualTo(Date value) {
            addCriterion("comreview_time <=", value, "comreviewTime");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeIn(List<Date> values) {
            addCriterion("comreview_time in", values, "comreviewTime");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeNotIn(List<Date> values) {
            addCriterion("comreview_time not in", values, "comreviewTime");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeBetween(Date value1, Date value2) {
            addCriterion("comreview_time between", value1, value2, "comreviewTime");
            return (Criteria) this;
        }

        public Criteria andComreviewTimeNotBetween(Date value1, Date value2) {
            addCriterion("comreview_time not between", value1, value2, "comreviewTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comreview
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comreview
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}