package com.neu.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table comreview
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Comreview {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comreview.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comreview.user_id
     *
     * @mbg.generated
     */
    private User user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comreview.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comreview.goods_id
     *
     * @mbg.generated
     */
    private Commodity commodity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comreview.comreview_time
     *
     * @mbg.generated
     */
    private Date comreviewTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comreview.id
     *
     * @return the value of comreview.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comreview.id
     *
     * @param id the value for comreview.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comreview.user_id
     *
     * @return the value of comreview.user_id
     *
     * @mbg.generated
     */
    public User getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comreview.user_id
     *
     * @param user the value for comreview.user_id
     *
     * @mbg.generated
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comreview.content
     *
     * @return the value of comreview.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comreview.content
     *
     * @param content the value for comreview.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comreview.goods_id
     *
     * @return the value of comreview.goods_id
     *
     * @mbg.generated
     */
    public Commodity getCommodity() {
        return commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comreview.goods_id
     *
     * @param commodity the value for comreview.goods_id
     *
     * @mbg.generated
     */
    public void setCommodity(Commodity commodity) {
        this.commodity = commodity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comreview.comreview_time
     *
     * @return the value of comreview.comreview_time
     *
     * @mbg.generated
     */
    public Date getComreviewTime() {
        return comreviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comreview.comreview_time
     *
     * @param comreviewTime the value for comreview.comreview_time
     *
     * @mbg.generated
     */
    public void setComreviewTime(Date comreviewTime) {
        this.comreviewTime = comreviewTime;
    }
}