package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table constanttype
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ConstantType {

	/**
	 * Database Column Remarks: ID主键 This field was generated by MyBatis Generator. This field corresponds to the database column constanttype.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 常数类别名称 This field was generated by MyBatis Generator. This field corresponds to the database column constanttype.name
	 * @mbg.generated
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column constanttype.id
	 * @return  the value of constanttype.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column constanttype.id
	 * @param id  the value for constanttype.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column constanttype.name
	 * @return  the value of constanttype.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column constanttype.name
	 * @param name  the value for constanttype.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}
}