package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table constantitem
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ConstantItem {

	/**
	 * Database Column Remarks: ID主键 This field was generated by MyBatis Generator. This field corresponds to the database column constantitem.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 所属常数类别ID This field was generated by MyBatis Generator. This field corresponds to the database column constantitem.ConstantTypeID
	 * @mbg.generated
	 */
	private ConstantType constantType;
	/**
	 * Database Column Remarks: 常数项名称 This field was generated by MyBatis Generator. This field corresponds to the database column constantitem.name
	 * @mbg.generated
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column constantitem.id
	 * @return  the value of constantitem.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column constantitem.id
	 * @param id  the value for constantitem.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column constantitem.ConstantTypeID
	 * @return  the value of constantitem.ConstantTypeID
	 * @mbg.generated
	 */
	public ConstantType getConstantType() {
		return constantType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column constantitem.ConstantTypeID
	 * @param constantType  the value for constantitem.ConstantTypeID
	 * @mbg.generated
	 */
	public void setConstantType(ConstantType constantType) {
		this.constantType = constantType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column constantitem.name
	 * @return  the value of constantitem.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column constantitem.name
	 * @param name  the value for constantitem.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name;
	}
}