package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table constant_type
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ConstantType {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constant_type.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   邮寄方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constant_type.mailing_method
     *
     * @mbg.generated
     */
    private String mailingMethod;

    /**
     * Database Column Remarks:
     *   支付方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constant_type.pattern_payment
     *
     * @mbg.generated
     */
    private String patternPayment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constant_type.id
     *
     * @return the value of constant_type.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constant_type.id
     *
     * @param id the value for constant_type.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constant_type.mailing_method
     *
     * @return the value of constant_type.mailing_method
     *
     * @mbg.generated
     */
    public String getMailingMethod() {
        return mailingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constant_type.mailing_method
     *
     * @param mailingMethod the value for constant_type.mailing_method
     *
     * @mbg.generated
     */
    public void setMailingMethod(String mailingMethod) {
        this.mailingMethod = mailingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constant_type.pattern_payment
     *
     * @return the value of constant_type.pattern_payment
     *
     * @mbg.generated
     */
    public String getPatternPayment() {
        return patternPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constant_type.pattern_payment
     *
     * @param patternPayment the value for constant_type.pattern_payment
     *
     * @mbg.generated
     */
    public void setPatternPayment(String patternPayment) {
        this.patternPayment = patternPayment;
    }
}