package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table information_management
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class InformationManagement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_management.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_management.information
     *
     * @mbg.generated
     */
    private String information;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_management.id
     *
     * @return the value of information_management.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_management.id
     *
     * @param id the value for information_management.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_management.information
     *
     * @return the value of information_management.information
     *
     * @mbg.generated
     */
    public String getInformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_management.information
     *
     * @param information the value for information_management.information
     *
     * @mbg.generated
     */
    public void setInformation(String information) {
        this.information = information;
    }
}