package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table largercategory
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LargerCategory {
    /**
     * Database Column Remarks:
     *   ID主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column largercategory.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   商品类别名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column largercategory.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column largercategory.id
     *
     * @return the value of largercategory.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column largercategory.id
     *
     * @param id the value for largercategory.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column largercategory.type_name
     *
     * @return the value of largercategory.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column largercategory.type_name
     *
     * @param typeName the value for largercategory.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }
}