package com.neu.entity;

import java.util.ArrayList;
import java.util.List;

public class MailingListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    public MailingListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameIsNull() {
            addCriterion("recipients_name is null");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameIsNotNull() {
            addCriterion("recipients_name is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameEqualTo(String value) {
            addCriterion("recipients_name =", value, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameNotEqualTo(String value) {
            addCriterion("recipients_name <>", value, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameGreaterThan(String value) {
            addCriterion("recipients_name >", value, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameGreaterThanOrEqualTo(String value) {
            addCriterion("recipients_name >=", value, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameLessThan(String value) {
            addCriterion("recipients_name <", value, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameLessThanOrEqualTo(String value) {
            addCriterion("recipients_name <=", value, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameLike(String value) {
            addCriterion("recipients_name like", value, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameNotLike(String value) {
            addCriterion("recipients_name not like", value, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameIn(List<String> values) {
            addCriterion("recipients_name in", values, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameNotIn(List<String> values) {
            addCriterion("recipients_name not in", values, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameBetween(String value1, String value2) {
            addCriterion("recipients_name between", value1, value2, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andRecipientsNameNotBetween(String value1, String value2) {
            addCriterion("recipients_name not between", value1, value2, "recipientsName");
            return (Criteria) this;
        }

        public Criteria andPostcodeIsNull() {
            addCriterion("postcode is null");
            return (Criteria) this;
        }

        public Criteria andPostcodeIsNotNull() {
            addCriterion("postcode is not null");
            return (Criteria) this;
        }

        public Criteria andPostcodeEqualTo(Integer value) {
            addCriterion("postcode =", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotEqualTo(Integer value) {
            addCriterion("postcode <>", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeGreaterThan(Integer value) {
            addCriterion("postcode >", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("postcode >=", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLessThan(Integer value) {
            addCriterion("postcode <", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeLessThanOrEqualTo(Integer value) {
            addCriterion("postcode <=", value, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeIn(List<Integer> values) {
            addCriterion("postcode in", values, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotIn(List<Integer> values) {
            addCriterion("postcode not in", values, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeBetween(Integer value1, Integer value2) {
            addCriterion("postcode between", value1, value2, "postcode");
            return (Criteria) this;
        }

        public Criteria andPostcodeNotBetween(Integer value1, Integer value2) {
            addCriterion("postcode not between", value1, value2, "postcode");
            return (Criteria) this;
        }

        public Criteria andCheckAddressIsNull() {
            addCriterion("Check_address is null");
            return (Criteria) this;
        }

        public Criteria andCheckAddressIsNotNull() {
            addCriterion("Check_address is not null");
            return (Criteria) this;
        }

        public Criteria andCheckAddressEqualTo(String value) {
            addCriterion("Check_address =", value, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andCheckAddressNotEqualTo(String value) {
            addCriterion("Check_address <>", value, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andCheckAddressGreaterThan(String value) {
            addCriterion("Check_address >", value, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andCheckAddressGreaterThanOrEqualTo(String value) {
            addCriterion("Check_address >=", value, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andCheckAddressLessThan(String value) {
            addCriterion("Check_address <", value, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andCheckAddressLessThanOrEqualTo(String value) {
            addCriterion("Check_address <=", value, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andCheckAddressLike(String value) {
            addCriterion("Check_address like", value, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andCheckAddressNotLike(String value) {
            addCriterion("Check_address not like", value, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andCheckAddressIn(List<String> values) {
            addCriterion("Check_address in", values, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andCheckAddressNotIn(List<String> values) {
            addCriterion("Check_address not in", values, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andCheckAddressBetween(String value1, String value2) {
            addCriterion("Check_address between", value1, value2, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andCheckAddressNotBetween(String value1, String value2) {
            addCriterion("Check_address not between", value1, value2, "checkAddress");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(Integer value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(Integer value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(Integer value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(Integer value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<Integer> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<Integer> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(Integer value1, Integer value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andMailingMethodIsNull() {
            addCriterion("mailing_method is null");
            return (Criteria) this;
        }

        public Criteria andMailingMethodIsNotNull() {
            addCriterion("mailing_method is not null");
            return (Criteria) this;
        }

        public Criteria andMailingMethodEqualTo(String value) {
            addCriterion("mailing_method =", value, "mailingMethod");
            return (Criteria) this;
        }

        public Criteria andMailingMethodNotEqualTo(String value) {
            addCriterion("mailing_method <>", value, "mailingMethod");
            return (Criteria) this;
        }

        public Criteria andMailingMethodGreaterThan(String value) {
            addCriterion("mailing_method >", value, "mailingMethod");
            return (Criteria) this;
        }

        public Criteria andMailingMethodGreaterThanOrEqualTo(String value) {
            addCriterion("mailing_method >=", value, "mailingMethod");
            return (Criteria) this;
        }

        public Criteria andMailingMethodLessThan(String value) {
            addCriterion("mailing_method <", value, "mailingMethod");
            return (Criteria) this;
        }

        public Criteria andMailingMethodLessThanOrEqualTo(String value) {
            addCriterion("mailing_method <=", value, "mailingMethod");
            return (Criteria) this;
        }

        public Criteria andMailingMethodLike(String value) {
            addCriterion("mailing_method like", value, "mailingMethod");
            return (Criteria) this;
        }

        public Criteria andMailingMethodNotLike(String value) {
            addCriterion("mailing_method not like", value, "mailingMethod");
            return (Criteria) this;
        }

        public Criteria andMailingMethodIn(List<String> values) {
            addCriterion("mailing_method in", values, "mailingMethod");
            return (Criteria) this;
        }

        public Criteria andMailingMethodNotIn(List<String> values) {
            addCriterion("mailing_method not in", values, "mailingMethod");
            return (Criteria) this;
        }

        public Criteria andMailingMethodBetween(String value1, String value2) {
            addCriterion("mailing_method between", value1, value2, "mailingMethod");
            return (Criteria) this;
        }

        public Criteria andMailingMethodNotBetween(String value1, String value2) {
            addCriterion("mailing_method not between", value1, value2, "mailingMethod");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mailing_list
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mailing_list
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}