package com.neu.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table order_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OrderInfo {
	/**
	 * Database Column Remarks: 编号
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column order_info.id
	 *
	 * @mbg.generated
	 */
	private Integer id;

	/**
	 * Database Column Remarks: 订单编号
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column order_info.order_number
	 *
	 * @mbg.generated
	 */
	private Integer orderNumber;

	/**
	 * Database Column Remarks: 下单时间
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column order_info.order_time
	 *
	 * @mbg.generated
	 */
	private Date orderTime;

	/**
	 * Database Column Remarks: 商品编号
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column order_info.goods_number
	 *
	 * @mbg.generated
	 */
	private Commodity commodity;

	/**
	 * Database Column Remarks: 用户id
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column order_info.user_id
	 *
	 * @mbg.generated
	 */
	private User user;

	/**
	 * Database Column Remarks: 应付金额
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column order_info.amount
	 *
	 * @mbg.generated
	 */
	private Double amount;

	/**
	 * Database Column Remarks: 用户是否付款(已付款，未付款，已过期)
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column order_info.status1
	 *
	 * @mbg.generated
	 */
	private ConstantItem constantItem1;

	/**
	 * Database Column Remarks: 商家是否发货
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column order_info.status2
	 *
	 * @mbg.generated
	 */
	private ConstantItem constantItem2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column order_info.id
	 *
	 * @return the value of order_info.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column order_info.id
	 *
	 * @param id
	 *            the value for order_info.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column order_info.order_number
	 *
	 * @return the value of order_info.order_number
	 *
	 * @mbg.generated
	 */
	public Integer getOrderNumber() {
		return orderNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column order_info.order_number
	 *
	 * @param orderNumber
	 *            the value for order_info.order_number
	 *
	 * @mbg.generated
	 */
	public void setOrderNumber(Integer orderNumber) {
		this.orderNumber = orderNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column order_info.order_time
	 *
	 * @return the value of order_info.order_time
	 *
	 * @mbg.generated
	 */
	public Date getOrderTime() {
		return orderTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column order_info.order_time
	 *
	 * @param orderTime
	 *            the value for order_info.order_time
	 *
	 * @mbg.generated
	 */
	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column order_info.goods_number
	 *
	 * @return the value of order_info.goods_number
	 *
	 * @mbg.generated
	 */
	public Commodity getCommodity() {
		return commodity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column order_info.goods_number
	 *
	 * @param commodity
	 *            the value for order_info.goods_number
	 *
	 * @mbg.generated
	 */
	public void setCommodity(Commodity commodity) {
		this.commodity = commodity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column order_info.user_id
	 *
	 * @return the value of order_info.user_id
	 *
	 * @mbg.generated
	 */
	public User getUser() {
		return user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column order_info.user_id
	 *
	 * @param user
	 *            the value for order_info.user_id
	 *
	 * @mbg.generated
	 */
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column order_info.amount
	 *
	 * @return the value of order_info.amount
	 *
	 * @mbg.generated
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column order_info.amount
	 *
	 * @param amount
	 *            the value for order_info.amount
	 *
	 * @mbg.generated
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column order_info.status1
	 *
	 * @return the value of order_info.status1
	 *
	 * @mbg.generated
	 */
	public ConstantItem getConstantItem1() {
		return constantItem1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column order_info.status1
	 *
	 * @param constantItem1
	 *            the value for order_info.status1
	 *
	 * @mbg.generated
	 */
	public void setConstantItem1(ConstantItem constantItem1) {
		this.constantItem1 = constantItem1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column order_info.status2
	 *
	 * @return the value of order_info.status2
	 *
	 * @mbg.generated
	 */
	public ConstantItem getConstantItem2() {
		return constantItem2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column order_info.status2
	 *
	 * @param constantItem2
	 *            the value for order_info.status2
	 *
	 * @mbg.generated
	 */
	public void setConstantItem2(ConstantItem constantItem2) {
		this.constantItem2 = constantItem2;
	}

	public OrderInfo(Integer orderNumber, Date orderTime, Commodity commodity, User user, Double amount) {
		super();
		this.orderNumber = orderNumber;
		this.orderTime = orderTime;
		this.commodity = commodity;
		this.user = user;
		this.amount = amount;
	}

	public OrderInfo() {
		super();
		// TODO Auto-generated constructor stub
	}
}