package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table public_management
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class PublicManagement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_management.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public_management.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_management.id
     *
     * @return the value of public_management.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_management.id
     *
     * @param id the value for public_management.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public_management.message
     *
     * @return the value of public_management.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public_management.message
     *
     * @param message the value for public_management.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message;
    }
}