package com.neu.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_menu
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class RoleMenuKey {
    /**
     * Database Column Remarks:
     *   角色编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.role_id
     *
     * @mbg.generated
     */
    private Role role;

    /**
     * Database Column Remarks:
     *   菜单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.menu_id
     *
     * @mbg.generated
     */
    private Menu menu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.role_id
     *
     * @return the value of role_menu.role_id
     *
     * @mbg.generated
     */
    @JsonIgnore
    public Role getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.role_id
     *
     * @param role the value for role_menu.role_id
     *
     * @mbg.generated
     */
    public void setRole(Role role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.menu_id
     *
     * @return the value of role_menu.menu_id
     *
     * @mbg.generated
     */
    public Menu getMenu() {
        return menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.menu_id
     *
     * @param menu the value for role_menu.menu_id
     *
     * @mbg.generated
     */
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
}