package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table securityquestion
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Securityquestion {
    /**
     * Database Column Remarks:
     *   自增序号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column securityquestion.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column securityquestion.user_id
     *
     * @mbg.generated
     */
    private User user;

    /**
     * Database Column Remarks:
     *   密保问题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column securityquestion.question
     *
     * @mbg.generated
     */
    private String question;

    /**
     * Database Column Remarks:
     *   密保答案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column securityquestion.answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column securityquestion.id
     *
     * @return the value of securityquestion.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column securityquestion.id
     *
     * @param id the value for securityquestion.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column securityquestion.user_id
     *
     * @return the value of securityquestion.user_id
     *
     * @mbg.generated
     */
    public User getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column securityquestion.user_id
     *
     * @param user the value for securityquestion.user_id
     *
     * @mbg.generated
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column securityquestion.question
     *
     * @return the value of securityquestion.question
     *
     * @mbg.generated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column securityquestion.question
     *
     * @param question the value for securityquestion.question
     *
     * @mbg.generated
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column securityquestion.answer
     *
     * @return the value of securityquestion.answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column securityquestion.answer
     *
     * @param answer the value for securityquestion.answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }
}