package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table smallcategory
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class SmallCategory {
    /**
     * Database Column Remarks:
     *   ID主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smallcategory.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   小商品类别名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smallcategory.type_name
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smallcategory.type_no
     *
     * @mbg.generated
     */
    private LargerCategory largercategory;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smallcategory.id
     *
     * @return the value of smallcategory.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smallcategory.id
     *
     * @param id the value for smallcategory.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smallcategory.type_name
     *
     * @return the value of smallcategory.type_name
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smallcategory.type_name
     *
     * @param typeName the value for smallcategory.type_name
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smallcategory.type_no
     *
     * @return the value of smallcategory.type_no
     *
     * @mbg.generated
     */
    public LargerCategory getLargercategory() {
        return largercategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smallcategory.type_no
     *
     * @param largercategory the value for smallcategory.type_no
     *
     * @mbg.generated
     */
    public void setLargercategory(LargerCategory largercategory) {
        this.largercategory = largercategory;
    }
}